name: "cd pipeline"

on:
    workflow_run:
        workflows: ["react ci pipeline"]
        types:
            - completed
        branches:
            - main
            - master
    # workflow_dispatch:

permissions:
    actions: read
    contents: read

jobs:
    deploy:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        environment: production1

        steps:
            - name: "set up nodejs"
              uses: actions/setup-node@v4
              with:
                  node-version: '22.15.0'

            - name: "set up vercel cli"
              run: npm install -g vercel

            - name: "download artifact files"
              uses: actions/download-artifact@v4
              with:
                name: build
                run-id: ${{ github.event.workflow_run.id }}
                github-token: ${{ github.token }}
                path: dist

            - name: "verify downloaded artifact"
              run: ls -la dist

            - name: "deploy to vercel"
              run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN2 }} --name=cicdproject ./dist


          
# https://cicdproject-3gxfqg6yf-vishalmiriyala900-gmailcoms-projects.vercel.app